#version: '3'
services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  test:
    build:
      context: .
      target: test
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
