services:
  txWorker:
    build:
      context: .
      dockerfile: Dockerfile
    image: txworker:latest
    container_name: txWorker
    ports:
      - "8000:8000"
    volumes:
      - ~/transcribe:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              #command: python -m src.main
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always


